package com.vadmack.superheroes.entities;

import com.fasterxml.jackson.annotation.JsonView;
import com.vadmack.superheroes.Views;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Schema(description = "Comic entity")
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
@EqualsAndHashCode
@Entity
@Table(name = "comics")
public class Comic {

  @Schema(description = "The unique ID of the comic resource.")
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @JsonView(Views.WrapperComic.class)
  private Long id;

  @Schema(description = "The canonical title of the comic. Autogenerated.")
  @Column(name = "title")
  @JsonView(Views.WrapperComic.class)
  private String title;

  @Schema(description = "The canonical URL identifier for this resource.")
  @Column(name = "resourceURI")
  private String resourceURI;

  @Schema(description = "Comic entity")
  @EqualsAndHashCode.Exclude
  @ManyToMany(fetch = FetchType.LAZY, cascade = {CascadeType.MERGE, CascadeType.PERSIST})
  private Set<Character> characters;

  @Schema(description = "The representative image for this comic.")
  @Column(name = "thumbnail")
  private String thumbnail;

}
